partyBundle\Entity\Participation:
    type: entity
    table: null
    repositoryClass: partyBundle\Entity\ParticipationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        paiement:
            type: boolean
        participation:
            type: boolean
    lifecycleCallbacks: {  }
