partyBundle\Entity\Party:
    type: entity
    table: null
    repositoryClass: partyBundle\Entity\PartyRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        date:
            type: datetime
        lieu:
            type: string
            length: 255
        nblimit:
            type: integer
    lifecycleCallbacks: {  }
    manyToMany:
        User:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            mappedBy: party
#    manyToMany:
#        Party:
#            targetEntity: partyBundle\Entity\Party
#            joinTable:
#                name: participation
#                joinColumns:
#                    party_id:
#                        referencedColumnName: id
#                inverseJoinColumns:
#                    user_id:
#                        referencedColumnName: id
