partyBundle\Entity\Participation:
    type: entity
    table: null
    repositoryClass: partyBundle\Entity\ParticipationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }

    manyToOne:
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
        party:
            targetEntity: partyBundle\Entity\Party
            joinColumn:
                name: party_id
                referencedColumnName: id