<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $user;


    /**
     * Add user
     *
     * @param \Application\Sonata\UserBundle\Entity\User $user
     *
     * @return User
     */
    public function addUser(\Application\Sonata\UserBundle\Entity\User $user)
    {
        $this->user[] = $user;

        return $this;
    }

    /**
     * Remove user
     *
     * @param \Application\Sonata\UserBundle\Entity\User $user
     */
    public function removeUser(\Application\Sonata\UserBundle\Entity\User $user)
    {
        $this->user->removeElement($user);
    }

    /**
     * Get user
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getUser()
    {
        return $this->user;
    }
    /**
     * @var \Application\Sonata\UserBundle\Entity\Party
     */
    private $party;


    /**
     * Set party
     *
     * @param \Application\Sonata\UserBundle\Entity\Party $party
     *
     * @return User
     */
    public function setParty(\Application\Sonata\UserBundle\Entity\Party $party = null)
    {
        $this->party = $party;

        return $this;
    }

    /**
     * Get party
     *
     * @return \Application\Sonata\UserBundle\Entity\Party
     */
    public function getParty()
    {
        return $this->party;
    }
    /**
     * @var \partyBundle\Entity\Participation
     */
    private $participation;


    /**
     * Set participation
     *
     * @param \partyBundle\Entity\Participation $participation
     *
     * @return User
     */
    public function setParticipation(\partyBundle\Entity\Participation $participation = null)
    {
        $this->participation = $participation;

        return $this;
    }

    /**
     * Get participation
     *
     * @return \partyBundle\Entity\Participation
     */
    public function getParticipation()
    {
        return $this->participation;
    }
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $participant;


    /**
     * Add participant
     *
     * @param \partyBundle\Entity\Party $participant
     *
     * @return User
     */
    public function addParticipant(\partyBundle\Entity\Party $participant)
    {
        $this->participant[] = $participant;

        return $this;
    }

    /**
     * Remove participant
     *
     * @param \partyBundle\Entity\Party $participant
     */
    public function removeParticipant(\partyBundle\Entity\Party $participant)
    {
        $this->participant->removeElement($participant);
    }

    /**
     * Get participant
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getParticipant()
    {
        return $this->participant;
    }
}
